# Generated by Django 5.0.2 on 2024-04-03 01:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('confirmation_number', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
            ],
        ),
    ]
